Repository AdrieanKhisbe/bundle-phobia-cli, pull requests merged in 2020-12, with the labels that each got.

#38 Fix README typo: thenumber
  README.md
Labels: Bug :bug:, Documentation :open_book:

#39 Restore coverage in the CI
  .nycrc
  package-lock.json
  package.json
Labels: Bug :bug:, Quality :microscope:

#37 Bugfix on Windows 10: command not working
  src/install.js
  src/npm-utils.js
Labels: Bug :bug:, Enhancement :lollipop:

#40 Fixed bundle-phobia-install not working
  src/install.js
  test/integration/install.integration.test.js
  test/integration/utils.js
Labels: Bug :bug:, Enhancement :lollipop:
